name: medgraph1
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - google-generativeai=0.8.3  # Phiên bản khả dụng
  - python-dotenv=1.0.1
  - streamlit=1.43.2
  - pdf2image
  - pdfminer-six
  - pytesseract
  - langchain=0.3.21
  - fastapi=0.110.1
  - uvicorn=0.29.0
  - requests=2.31.0
  - httpx=0.28.1
  - numpy=1.26.4
  - pandas=2.0.2
  - matplotlib=3.9.2
  - scikit-learn=1.5.1
  - pip:
      - protobuf==4.25.3  # Phiên bản khả dụng
      - torch==2.4.0
      - torchvision==0.19.0
      - langchain-google-genai==2.0.0
      - chromadb==0.4.24
      - neo4j==5.28.1
      - qdrant-client==1.10.1
      - pymilvus==2.4.5
      - sentence-transformers==3.0.1
      - unstructured==0.10.30
      - unstructured-inference==0.7.11
      - unstructured-pytesseract==0.3.12
      - pdfplumber==0.11.4